name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version override (leave empty to use project version)'
        required: false
        default: ''
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
        default: 'pypi'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'pypi' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry build wheel setuptools

    - name: Set version if specified
      if: ${{ github.event.inputs.version != '' }}
      run: |
        poetry version ${{ github.event.inputs.version }}
        echo "Updated version to ${{ github.event.inputs.version }}"

    - name: Build package
      run: |
        poetry build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: ${{ vars.SKIP_EXISTING || 'false' }}
